// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RespondioTestCasesTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() throws MalformedURLException {
    driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), DesiredCapabilities.chrome());
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void signIn2() {
    // Test name: SignIn-2
    // Step # | name | target | value
    // 1 | open | /user/login | 
    driver.get("https://app.respond.io/organization/241400/spaces/user/login");
    // 2 | setWindowSize | 1056x700 | 
    driver.manage().window().setSize(new Dimension(1056, 700));
    // 3 | click | id=input-7 | 
    driver.findElement(By.id("input-7")).click();
    // 4 | type | id=input-7 | ayesha.sajjad@live.com
    driver.findElement(By.id("input-7")).sendKeys("ayesha.sajjad@live.com");
    // 5 | click | css=.dls-h-icon-md > path | 
    driver.findElement(By.cssSelector(".dls-h-icon-md > path")).click();
    // 6 | click | id=input-9 | 
    driver.findElement(By.id("input-9")).click();
    // 7 | type | id=input-9 | Eternity2life@123
    driver.findElement(By.id("input-9")).sendKeys("Eternity2life@123");
    // 8 | click | css=.disabled\3A dls-cursor-not-allowed | 
    driver.findElement(By.cssSelector(".disabled\\3A dls-cursor-not-allowed")).click();
    // 9 | runScript | window.scrollTo(0,0) | 
    js.executeScript("window.scrollTo(0,0)");
  }
  @Test
  public void addNewWorkspace() {
    // Test name: Add_New_Workspace
    // Step # | name | target | value
    // 1 | open | https://app.respond.io/user/user-profile | 
    driver.get("https://app.respond.io/user/user-profile");
    // 2 | setWindowSize | 1060x700 | 
    driver.manage().window().setSize(new Dimension(1060, 700));
    // 3 | click | css=.v-list-item:nth-child(5) .dls-truncate | 
    driver.findElement(By.cssSelector(".v-list-item:nth-child(5) .dls-truncate")).click();
    // 4 | click | css=.dls-flex:nth-child(1) > .dls-shrink .dls-txt-button > span | 
    driver.findElement(By.cssSelector(".dls-flex:nth-child(1) > .dls-shrink .dls-txt-button > span")).click();
    // 5 | doubleClick | css=.v-overlay__scrim | 
    {
      WebElement element = driver.findElement(By.cssSelector(".v-overlay__scrim"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 6 | click | id=input-120 | 
    driver.findElement(By.id("input-120")).click();
    // 7 | type | id=input-120 | Test_Workspace_1
    driver.findElement(By.id("input-120")).sendKeys("Test_Workspace_1");
    // 8 | click | css=.v-btn:nth-child(3) .dls-txt-button | 
    driver.findElement(By.cssSelector(".v-btn:nth-child(3) .dls-txt-button")).click();
    // 9 | click | css=.float-end .dls-txt-button | 
    driver.findElement(By.cssSelector(".float-end .dls-txt-button")).click();
  }
  @Test
  public void signOut() {
    // Test name: Sign_Out
    // Step # | name | target | value
    // 1 | open | https://app.respond.io/organization/241400/spaces | 
    driver.get("https://app.respond.io/organization/241400/spaces");
    // 2 | setWindowSize | 1064x700 | 
    driver.manage().window().setSize(new Dimension(1064, 700));
    // 3 | click | css=.v-avatar > #isax-bold | 
    driver.findElement(By.cssSelector(".v-avatar > #isax-bold")).click();
    // 4 | click | css=.v-list-item:nth-child(8) .multi-line > .dls-txt-button | 
    driver.findElement(By.cssSelector(".v-list-item:nth-child(8) .multi-line > .dls-txt-button")).click();
    // 5 | close |  | 
    driver.close();
  }
}
